// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE-YWe2IN6eWldN5n7KqQmK3JyLYPds8s',
    appId: '1:496984038887:web:7db492c3e568cceb33b142',
    messagingSenderId: '496984038887',
    projectId: 'iyapp-794b8',
    authDomain: 'iyapp-794b8.firebaseapp.com',
    storageBucket: 'iyapp-794b8.appspot.com',
    measurementId: 'G-C6YYQNBYCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9qrYdhB-sIT0ro3howoNEdej30SNKQgo',
    appId: '1:496984038887:android:2320aa622278ebcb33b142',
    messagingSenderId: '496984038887',
    projectId: 'iyapp-794b8',
    storageBucket: 'iyapp-794b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPf-5wv40BKqkt8Ay315uwvcrfV_Ljb9w',
    appId: '1:496984038887:ios:b89acc941ca6058d33b142',
    messagingSenderId: '496984038887',
    projectId: 'iyapp-794b8',
    storageBucket: 'iyapp-794b8.appspot.com',
    iosClientId: '496984038887-792pli7sppm8t3dgighjd5no2jeie9g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPf-5wv40BKqkt8Ay315uwvcrfV_Ljb9w',
    appId: '1:496984038887:ios:b89acc941ca6058d33b142',
    messagingSenderId: '496984038887',
    projectId: 'iyapp-794b8',
    storageBucket: 'iyapp-794b8.appspot.com',
    iosClientId: '496984038887-792pli7sppm8t3dgighjd5no2jeie9g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.app2',
  );
}
